services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: xyz-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: xyz-tours
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - xyz-network

  # Redis
  redis:
    image: redis:7.2-alpine
    container_name: xyz-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - xyz-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: xyz-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017/xyz-tours
      REDIS_URL: redis://:redis123@redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - xyz-network

  # Frontend (Astro)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: xyz-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PUBLIC_API_URL: http://localhost:3000
      PUBLIC_SITE_URL: http://localhost:4321
    ports:
      - "3002:4321"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - xyz-network
    command: npm run preview -- --host 0.0.0.0

  # Admin PWA
  admin-pwa:
    build:
      context: ./admin-pwa
      dockerfile: Dockerfile
    container_name: xyz-admin-pwa
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PUBLIC_API_URL: http://localhost:3000
      PUBLIC_SITE_URL: http://localhost:3001
    ports:
      - "3003:3001"
    depends_on:
      - backend
    volumes:
      - ./admin-pwa:/app
      - /app/node_modules
    networks:
      - xyz-network
    command: npm run preview -- --host 0.0.0.0 --port 3001

volumes:
  mongodb_data:
  redis_data:

networks:
  xyz-network:
    driver: bridge
